/** @type {import('prettier').Config} */
module.exports = {
    // printWidth: 80,
    tabWidth: 4,
    // useTabs: false,
    // semi: true,
    singleQuote: true,
    // quoteProps: 'as-needed',
    jsxSingleQuote: true,
    // trailingComma: 'all',
    // bracketSpacing: true,
    // bracketSameLine: false,
    // arrowParens: 'always',
    // rangeStart: 0,
    // rangeEnd: Infinity,
    // parser: '',
    // filepath: '',
    // requirePragma: false,
    // insertPragma: false,
    // proseWrap: 'preserve',
    // htmlWhitespaceSensitivity: 'css',
    // vueIndentScriptAndStyle: false,
    // endOfLine: 'lf',
    // embeddedLanguageFormatting: 'auto',
    // singleAttributePerLine: false,
    plugins: ['prettier-plugin-tailwindcss'],
};
